version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    steps:
      - checkout
      - run: # print the name of the branch we're on
        name: "What branch am I on?"
        command: echo ${CIRCLE_BRANCH}
      - run: ssh -oStrictHostKeyChecking=no -v root@139.180.155.155 "./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main